import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';

import { cn } from '@/lib/utils';
import Navbar from '@/components/layout/nav/Navbar';
import Footer from '@/components/layout/Footer';
import Feedbackmodal from '@/components/feedback/Feedbackmodal';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <Navbar />
        {children}
        <Feedbackmodal />
        <Footer />
      </body>
    </html>
  );
}
