import type { Metadata } from 'next';

import Navbar from '@/components/layout/nav/Navbar';
import Footer from '@/components/layout/Footer';
import Feedbackmodal from '@/components/feedback/Feedbackmodal';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-grow">{children}</main>
      <Feedbackmodal />
      <Footer />
    </div>
  );
}
